trigger:
  - master
  - dev

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageNmae: "vs2017-win2016"

pool:
  vmImage: ${imageName}

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - bash: |
      echo ">>> Compile vscode-test"
      yarn && yarn compile
      echo ">>> Conpiled vscode-test"
      echo ">>> Run integration test"
      yarn && yarn compile && yarn test
    displayName: Run Tests
    env:
      DISPLAY: "99.0"
